name: Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  merge_group:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    name: Run all checks
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Evaluate Nix checks
        run: nix flake check "github:${GITHUB_REPOSITORY}/${GITHUB_SHA}"
